Monitor.Web/Areas/Manage/Controllers/ClusterController.cs
using Monitor.Domain.Cluster.Dal;
using Monitor.Domain.PlatformManage.Dal;
using Monitor.Domain.PlatformManage.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Webdiyer.WebControls.Mvc;
using BSF.Db;

namespace Web.Areas.Manage.Controllers
{
    [AuthorityCheck(Roles = "Admin")]
    public class ClusterController : Controller
    {
        //
        // GET: /Manage/Manage/

        public ActionResult Index(string id,string keyword, string CStime, string CEtime, int pagesize = 10, int pageindex = 1)
        {
            ViewBag.keyword = keyword;
            ViewBag.CStime = CStime;
            ViewBag.CEtime = CEtime;
            ViewBag.pagesize = pagesize;
            ViewBag.pageindex = pageindex;
            ViewBag.SqlTimeNow = DateTime.Now;
            ViewBag.id = id;
            tb_cluster_dal dal = new tb_cluster_dal();
            PagedList<tb_cluster_model> pageList = null;
            int count = 0;
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                List<tb_cluster_model> List = dal.GetList(PubConn, id,keyword, CStime, CEtime, pagesize, pageindex, out count);
                using (DbConn MonitorConn = DbConn.CreateConn(Config.ClusterConnectString))
                {
                    MonitorConn.Open();
                    tb_cluster_monitorinfo_dal monitordal = new tb_cluster_monitorinfo_dal();
                    for (int i = 0; i < List.Count; i++)
                    {
                        List[i].MonitorJson = monitordal.GetServerMonitorJson(MonitorConn, List[i].id);
                    }
                }
                pageList = new PagedList<tb_cluster_model>(List, pageindex, pagesize, count);
                ViewBag.SqlTimeNow = PubConn.GetServerDate();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(tb_cluster_model model)
        {
            tb_cluster_dal dal = new tb_cluster_dal();
            try
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    if (dal.CheckServerIp(PubConn, model.serverip))
                    {
                        CheckJsonFormat(model);
                        model.createtime = PubConn.GetServerDate();
                        model.lastupdatetime = PubConn.GetServerDate();
                        model.onlinetime = PubConn.GetServerDate().AddDays(-1);
                        dal.Add(PubConn, model);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "IP已存在");
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        public ActionResult Update(int id)
        {
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                tb_cluster_model model = new tb_cluster_dal().Get(PubConn, id);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Update(tb_cluster_model model)
        {
            try
            {
                tb_cluster_dal dal = new tb_cluster_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    if (dal.CheckServerIp(PubConn, model.serverip,model.id))
                    {
                        CheckJsonFormat(model);
                        model.onlinetime = PubConn.GetServerDate().AddDays(-1);
                        model.lastupdatetime = PubConn.GetServerDate();
                        dal.Update(PubConn, model);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "IP已存在");
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        private void CheckJsonFormat(tb_cluster_model model)
        {
            if (!string.IsNullOrWhiteSpace(model.monitorcollectconfigjson))
            {
                try {
                    new BSF.Serialization.JsonProvider().Deserialize<List<Monitor.Core.CollectConfig>>(model.monitorcollectconfigjson);
                }
                catch (Exception exp)
                {
                    throw new Exception("监控配置json格式不对");
                }
            }
            if (!string.IsNullOrWhiteSpace(model.performancecollectconfigjson))
            {
                try
                {
                    new BSF.Serialization.JsonProvider().Deserialize<List<Monitor.Core.CollectConfig>>(model.performancecollectconfigjson);
                }
                catch (Exception exp)
                {
                    throw new Exception("性能检测配置json格式不对");
                }
            }
        }

        public JsonResult Delete(int id)
        {
            try
            {
                tb_cluster_dal dal = new tb_cluster_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    var o = dal.Get(PubConn, id);
                    if ((PubConn.GetServerDate() - o.onlinetime) < TimeSpan.FromSeconds(10))
                    {
                        throw new Exception("请先关闭监控，并确认当前服务器的服务已停止！");
                    }
                    dal.Delete(PubConn, id);
                    return Json(new { code = 1, msg = "Success" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { code = -1, msg = ex.Message });
            }
        }
    }
}

Monitor.Web/Areas/Manage/Controllers/ConfigController.cs
using Monitor.Domain.PlatformManage.Dal;
using Monitor.Domain.PlatformManage.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Webdiyer.WebControls.Mvc;
using BSF.Db;

namespace Web.Areas.Manage.Controllers
{
    [AuthorityCheck(Roles = "Admin")]
    public class ConfigController : Controller
    {
        //
        // GET: /Manage/Config/

        public ActionResult Index(string keyword,int pageindex=1,int pagesize=10)
        {
            ViewBag.keyword = keyword;
            ViewBag.pagesize = pagesize;
            ViewBag.pageindex = pageindex;
            tb_keyvalue_config_dal dal = new tb_keyvalue_config_dal();
            PagedList<tb_keyvalue_config_model> pageList = null;
            int count = 0;
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                List<tb_keyvalue_config_model> List = dal.GetList(PubConn, keyword, pagesize, pageindex, out count);
                pageList = new PagedList<tb_keyvalue_config_model>(List, pageindex, pagesize, count);
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(tb_keyvalue_config_model model)
        {
            tb_keyvalue_config_dal dal = new tb_keyvalue_config_dal();
            try
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    dal.Add(PubConn, model);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        public ActionResult Update(int id)
        {
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                tb_keyvalue_config_model model = new tb_keyvalue_config_dal().Get(PubConn, id);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Update(tb_keyvalue_config_model model)
        {
            tb_keyvalue_config_dal dal = new tb_keyvalue_config_dal();
            try
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    dal.Edit(PubConn, model);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        public JsonResult Delete(int id)
        {
            try
            {
                tb_keyvalue_config_dal dal = new tb_keyvalue_config_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    dal.Delete(PubConn, id);
                    return Json(new { code = 1, msg = "Success" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { code = -1, msg = ex.Message });
            }
        }
    }
}

Monitor.Web/Areas/Manage/Controllers/UserController.cs
using Monitor.Domain.PlatformManage.Dal;
using Monitor.Domain.PlatformManage.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using BSF.Db;
using BSF.Extensions;

namespace Web.Areas.Manage.Controllers
{
    [AuthorityCheck(Roles = "Admin")]
    public class UserController : Controller
    {
        //
        // GET: /Manage/User/

        public ActionResult Index()
        {
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                List<tb_user_model> Model = new tb_user_dal().GetAllUsers(PubConn);
                return View(Model);
            }
        }

        public ActionResult Add(int? userid)
        {
            if (userid == null)
                return View();
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                tb_user_dal dal = new tb_user_dal();

                var model = dal.Get(PubConn, userid.Value);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Add(tb_user_model model)
        {
            using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
            {
                PubConn.Open();
                tb_user_dal dal = new tb_user_dal();
                model.usercreatetime = DateTime.Now;
                model.lastsenderrortime = DateTime.Now;
                model.errorsendintervaltime =( model.errorsendintervaltime==0?1:model.errorsendintervaltime);
                model.usertel = model.usertel.NullToEmpty();
                model.useremail = model.useremail.NullToEmpty();
                if (model.id == 0)
                    dal.Add(PubConn, model);
                else
                    dal.Edit(PubConn, model);
            }
            return RedirectToAction("index");
        }

        public JsonResult Delete(int id)
        {
            try
            {
                tb_user_dal dal = new tb_user_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.PlatformManageConnectString))
                {
                    PubConn.Open();
                    bool state = dal.Delete(PubConn, id);
                    return Json(new { code = 1, state = state });
                }
            }
            catch (Exception ex)
            {
                return Json(new { code = -1, msg = ex.Message });
            }
        }
    }
}

Monitor.Web/Areas/UnityLog/Controllers/LogController.cs
using Monitor.Domain.UnityLog.Dal;
using Monitor.Domain.UnityLog.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Webdiyer.WebControls.Mvc;
using BSF.Db;

namespace Web.Areas.UnityLog.Controllers
{
    [AuthorityCheck]
    public class LogController : Controller
    {
        //
        // GET: /UnityLog/Log/

        public ActionResult Index(string id, string keyword, string timebegin,string timeend, string projectname,int logtype=-1, int pageindex = 1, int pagesize = 10)
        {
            ViewBag.keyword = keyword; ViewBag.logtype = logtype; ViewBag.projectname = projectname;
            ViewBag.id = id;
            if (!string.IsNullOrWhiteSpace(timebegin))
                ViewBag.timebegin = DateTime.Parse(timebegin);
            else
                ViewBag.timebegin = DateTime.Now.Date;
            if (!string.IsNullOrWhiteSpace(timeend))
                ViewBag.timeend = DateTime.Parse(timeend);
            else
                ViewBag.timeend = DateTime.Now.Date.AddDays(1);
            tb_log_dal dal = new tb_log_dal();
            PagedList<tb_log_model> pageList = null;
            int count = 0;
            using (DbConn PubConn = DbConn.CreateConn(Config.UnityLogConnectString))
            {
                PubConn.Open();
                List<tb_log_model> List = new List<tb_log_model>();
                try
                {
                    List = dal.GetList(PubConn,id, keyword, ViewBag.timebegin, ViewBag.timeend,logtype,projectname, pagesize, pageindex, out count);
                }
                catch
                {
                    List = new List<tb_log_model>();
                }
                pageList = new PagedList<tb_log_model>(List, pageindex, pagesize, count);
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }
    }
}

Monitor.Web/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/css.css" rel="stylesheet" />
    <link href="~/Content/HighChartPackCss.css" rel="stylesheet" />
@*        <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" />*@
        <script src="~/Scripts/jquery-1.8.0.min.js" type="text/javascript"></script>
@*    <script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>*@

    <script src="~/Scripts/DatePicker/WdatePicker.js"></script>
    <script src="~/Content/js/common.js"></script>
    @RenderSection("Styles", false)
    @RenderSection("Scripts", false)
</head>
<body>
     <div class="header">
        <span style="color: white; font-size: 25px; margin-left: 25px; font-weight: bold; font-family: 微软雅黑;">监控平台</span>
        <div class="fr mr10">
            
            <span id="toptips" class="remind fl"><span id="toptips1"></span></span>
            @if (Monitor.Web.Models.UserLoginInfo.CurrentUserLoginInfo!=null)
            {
                <a href="/login/logout" class="fl">退出</a>
            }
            else
            {
                <a href="/login/login" class="fl">登录</a>
            }
        </div>
    </div>
    <div class="content w">
        <div class="leftmenu fl">
            <ul class="level1">
                @if(Convert.ToInt32(Monitor.Web.Models.UserLoginInfo.CurrentUserLoginInfo.UserModel.userrole)==(int)BSF.BaseService.Monitor.SystemRuntime.EnumUserRole.Admin)
                {
                <li>
                    <p>参数配置管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("index", "Cluster", new { area="Manage" })">监控服务器</a></li>
                        <li><a href="@Url.Action("index", "Config", new { area="Manage" })">配置字典</a></li>
                        <li><a href="@Url.Action("index", "User", new { area="Manage" })">用户管理  </a></li>
                        <li><a href="@Url.Action("index", "ClusterCollectVersion", new { area="Manage" })">服务器采集Dll版本</a></li>
                        <li><a href="@Url.Action("index", "DataBaseConfig", new { area="Manage" })">数据库配置</a></li>
                    </ul>
                </li>
                }
                <li>
                    <p>耗时监控管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("index", "TimeWatchLogSqlDayReport", new { area="TimeWatchCustomer" })">SQL月耗时表</a></li>
                        <li><a href="@Url.Action("index", "TimeWatchLogApiDayReport", new { area="TimeWatchCustomer" })">API月耗时表</a></li>
@*                        <li><a href="@Url.Action("index", "TimeWatchLogSql", new { area="TimeWatchCustomer" })">SQL日耗时表</a></li>
                        <li><a href="@Url.Action("index", "TimeWatchLogApi", new { area="TimeWatchCustomer" })">Api日耗时表</a></li>*@
                        <li><a href="@Url.Action("Chart", "TimeWatchLog", new { area="TimeWatchCustomer" })">耗时性能图</a></li>
                        <li><a href="@Url.Action("index", "TimeWatchLog", new { area="TimeWatchCustomer" })">耗时查询</a></li>
                        <li><a href="@Url.Action("index", "SqlHashContrastUrl", new { area="TimeWatchCustomer" })">URL/Sql对照表</a></li>
                        <li><a href="@Url.Action("index", "SqlHashConsult", new { area="TimeWatchCustomer" })">SQL参照表</a></li>
                        <li><a href="@Url.Action("index", "SqlHashNoParam", new { area="TimeWatchCustomer" })">问题SQL列表</a></li>
                    </ul>
                </li>
                 <li>
                    <p>集群监控管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("index", "PerformanceCollect", new { area="Cluster" })">服务器日性能表</a></li>
                        <li><a href="@Url.Action("index", "PerformanceDayReport", new { area="Cluster" })">服务器月性能表</a></li>
                        <li><a href="@Url.Action("Chart", "PerformanceCollect", new { area="Cluster" })">服务器性能图</a></li>
                        <li><a href="@Url.Action("index", "MonitorInfo", new { area="Cluster" })">服务器监控信息</a></li>
                        <li><a href="@Url.Action("index", "MonitorInfoSnapshot", new { area="Cluster" })">服务器监控快照</a></li>
                    </ul>
                </li>
                <li>
                    <p>统一日志管理<i></i></p>
                    <ul class="level2">
                        <li><a href="@Url.Action("index", "Log", new { area="UnityLog" })">统一日志</a></li>
                        <li><a href="@Url.Action("index", "ErrorLog", new { area="UnityLog" })">错误日志</a></li>
                    </ul>
                </li>
               
            </ul>
        </div>
        <div class="main_cont">
            @RenderBody()
        </div>
    </div>
</body>
</html>