Monitor.Web/Areas/TimeWatchCustomer/Controllers/SqlHashContrastUrlController.cs
using Monitor.Domain.TimeWatch.Dal;
using Monitor.Domain.TimeWatch.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Webdiyer.WebControls.Mvc;
using BSF.Db;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    public class SqlHashContrastUrlController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/SqlHashContrastUrl/

        public ActionResult Index(string sqlhash, string sql, string url, string orderby = "", int connid = 0, int pagesize = 10, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                ViewBag.sqlhash = sqlhash; ViewBag.sql = sql; ViewBag.url = url; ViewBag.orderby = orderby;
                tb_sqlhash_url_contrast_dal dal = new tb_sqlhash_url_contrast_dal();
                PagedList<tb_sqlhash_url_contrast_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConn.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_sqlhash_url_contrast_model> List = dal.GetList(PubConn, sqlhash, sql, url, orderby, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_sqlhash_url_contrast_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

    }
}

Monitor.Web/Areas/TimeWatchCustomer/Controllers/TimeWatchLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Monitor.Domain.TimeWatch.Model;
using Monitor.Domain.TimeWatch.Dal;
using Webdiyer.WebControls.Mvc;
using BSF.Db;
using Web.Models;
using Monitor.Domain.Chart.Model;

namespace Web.Areas.TimeWatchCustomer.Controllers
{
    [AuthorityCheck]
    public class TimeWatchLogController : TimeWatchConnVisit
    {
        //
        // GET: /TimeWatchCustomer/TimeWatchLog/

        public ActionResult Index(string timebegin, string timeend, string projectname, string fromip, string sqlip, string url, string logtag,string orderby, int logtype = -1, double timewatchmin = -1, double timewatchmax = -1, int connid = 0, int pagesize = 10, int pageindex = 1)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(timebegin))
                    timebegin = DateTime.Now.AddHours(-1).ToString("yyyy-MM-dd HH:mm:ss");
                if (string.IsNullOrWhiteSpace(timeend))
                    timeend = DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss");
                ViewBag.timebegin = timebegin; ViewBag.timeend = timeend; ViewBag.timewatchmin = (timewatchmin == -1 ? "" : timewatchmin + ""); ViewBag.timewatchmax = (timewatchmax == -1 ? "" : timewatchmax + ""); ViewBag.projectname = projectname; ViewBag.logtype = logtype;
                ViewBag.fromip = fromip; ViewBag.sqlip = sqlip; ViewBag.logtag = logtag; ViewBag.orderby = orderby; ViewBag.url = url;
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                PagedList<tb_timewatchlog_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConn.CreateConn(conn))
                {
                    PubConn.Open();
                    List<tb_timewatchlog_model> List = dal.GetList(PubConn, timebegin, timeend, timewatchmin, timewatchmax, projectname, logtype, logtag, fromip, sqlip, orderby, url,pagesize, pageindex, out count);
                    pageList = new PagedList<tb_timewatchlog_model>(List, pageindex, pagesize, count);
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }
                return View(pageList);
            });
        }

        //public ActionResult Chart(string key, int type = 1, int connid = 0)
        //{
        //    return this.ConnVisit(connid, (conn) =>
        //    {
        //        ViewBag.Key = key;
        //        ViewBag.Type = type;
        //        return View();
        //    });
        //}

        public ActionResult ChartLoad(string key, int num = -3, int connid = 0, int type = 1)
        { 
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                using (DbConn PubConn = DbConn.CreateConn(conn))
                {
                    PubConn.Open();
                    Dictionary<string, List<ChartMainModel>> model = dal.GetMainChartJson(PubConn, num, key, type);
                    return Json(new { code = 1, data = model });
                }
            });
        }

        public ActionResult ChartJson(int connid, string Fday,string Nday, string key, string columnname)
        {
            return this.ConnVisit(connid, (conn) =>
            {
                if (string.IsNullOrWhiteSpace(key))
                {
                    return Json(new { code = -1, msg = "参数丢失" });
                }
                if (string.IsNullOrWhiteSpace(columnname))
                {
                    return Json(new { code = -1, msg = "请选择比较的参数" });
                }
                try
                {
                    List<string> day = new List<string>();
                    day.Add(Fday);
                    day.Add(Nday);
                    tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                    Dictionary<string, List<ChartSubModel>> model = new Dictionary<string, List<ChartSubModel>>();
                    using (DbConn PubConn = DbConn.CreateConn(conn))
                    {
                        PubConn.Open();
                        model = dal.GetSubChartJson(PubConn, day, key, columnname);
                    }
                    return Json(new { code = 1, data = model });
                }
                catch (Exception ex)
                {
                    return Json(new { code = -1, msg = "日表不存在无法比较" });
                }
            });
        }

        public ActionResult Chart(string logtag, string date, BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType type= BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl, string datatype = "avg", int connid = 0, string columns="time")
        {
            return this.ConnVisit(connid, (conn) =>
          {
              if (string.IsNullOrWhiteSpace(date))
                  date = DateTime.Now.Date.ToString("yyyy-MM-dd");
              ViewBag.type = type; ViewBag.date = date; ViewBag.datatype = datatype; ViewBag.logtag = logtag; ViewBag.connid = connid; 
              List<TimeChartModel> ms = new List<TimeChartModel>();
              if (string.IsNullOrWhiteSpace(logtag))
              {
                  return View(ms);
              } 
              int a=0;
              if(!int.TryParse(logtag,out a))
              {
                  type = BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl;
              }
              TimeChartDataType chartdatatype = (TimeChartDataType)Enum.Parse(typeof(TimeChartDataType), datatype);
              TimeChartType charttype = TimeChartType.Day;

              if (date.Split('-').Length == 3)
                  charttype = TimeChartType.Day;
              else if (date.Split('-').Length == 2)
                  charttype = TimeChartType.Month;
              else if (date.Split('-').Length == 1)
              {
                  charttype = TimeChartType.Year;
                  date = new DateTime(Convert.ToInt32(date), 1, 1, 0, 0, 0).ToString("yyyy-MM-dd");
              }

              var startDate = DateTime.Parse(date).Date;
              string[] cs = columns.TrimEnd(',').Split(',');

              foreach (var c in cs)
              {
                  if (c == "")
                      continue;
                  var model = new TimeChartModel();
                  model.DataType = chartdatatype;
                  model.Type = charttype;
                  model.StartDate = startDate;
                  model.Key = c;
                  model.Title = "耗时";
                  model.UnitText = "秒";
                  if (model.DataType == TimeChartDataType.count)
                      model.UnitText = "次";

                  model.SubTitle = model.Title + "【" + model.DataType.ToString() + "】值统计图";
                  if (model.Type == TimeChartType.Day)
                  {
                      model.PointInterval = "60 * 1000";//一分钟
                      model.EndDate = model.StartDate.AddDays(1);
                      model.MaxZoom = "60 * 60 * 1000";
                      model.SubTitle += ",采集单位【分钟】";
                  }
                  else if (model.Type == TimeChartType.Month)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddMonths(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }
                  else if (model.Type == TimeChartType.Year)
                  {
                      model.PointInterval = "24 * 60 * 60 * 1000";//一天
                      model.EndDate = model.StartDate.AddYears(1);
                      model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                      model.SubTitle += ",采集单位【天】";
                  }


                  Dictionary<DateTime, double> dic = new Dictionary<DateTime, double>();
                  using (DbConn PubConn = DbConn.CreateConn(conn))
                    {
                        if (model.Type == TimeChartType.Day)
                        {
                            if (type == BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dal dal = new tb_timewatchlog_api_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, logtag, model.DataType.ToString(), (int)type + "");
                            }
                            else if (type == BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            { 
                                tb_timewatchlog_dal dal = new tb_timewatchlog_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate,logtag, model.DataType.ToString(),(int)type+"");
                            }
                        }
                        else
                        {
                            if (type == BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl)
                            {
                                tb_timewatchlog_api_dayreport_dal dal = new tb_timewatchlog_api_dayreport_dal();
                                dic = dal.GetTimeChart(PubConn, c, model.StartDate, model.EndDate, logtag, model.DataType.ToString());
                            }
                            else if(type == BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd)
                            {
                                tb_timewatchlog_sql_dayreport_dal dal = new tb_timewatchlog_sql_dayreport_dal();

Monitor.Web/Areas/TimeWatchCustomer/Views/SqlHashContrastUrl/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Monitor.Domain.TimeWatch.Model.tb_sqlhash_url_contrast_model>
@{
    ViewBag.Title = "URL/Sql对照表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, Monitor.Domain.PlatformManage.Model.timewatchConnModel> dic =
        ViewBag.TimeWatchConn as Dictionary<int, Monitor.Domain.PlatformManage.Model.timewatchConnModel>;
}
<div class="head">
    <div class="title">
        URL/Sql对照表
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("index", "SqlHashContrastUrl", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))      
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                   
                    <li>
                        <label>URL</label>
                        <input type="text" name="url" value="@ViewBag.url" />
                    </li>
                     <li>
                        <label>sql哈希码</label>
                        <input type="text" name="sqlhash"  class="smalltext"  value="@ViewBag.sqlhash" />
                    </li>
                    <li>
                        <label>sql语句</label>
                        <input type="text" name="sql" value="@ViewBag.sql" />
                    </li>
                    <li>
                        <label>降序</label>
                        <select name="orderby">
                            <option value="" @(ViewBag.orderby+""==""?"selected='selected'":"")>URL</option>
                            <option value="avgtime" @(ViewBag.orderby+""=="avgtime"?"selected='selected'":"")>平均时间</option>
                            <option value="maxtime" @(ViewBag.orderby+""=="maxtime"?"selected='selected'":"")>最大时间</option>
                            <option value="mintime" @(ViewBag.orderby+""=="mintime"?"selected='selected'":"")>最小时间</option>
                             <option value="E.count" @(ViewBag.orderby+""=="E.count"?"selected='selected'":"")>调用次数</option>
                        </select>
                    </li>
                    <li>
                        <label>数据库</label>
                        <select name="connid">
                            @foreach (KeyValuePair<int, Monitor.Domain.PlatformManage.Model.timewatchConnModel> d in dic)
                            { 
                                <option value="@d.Key"@Html.Raw(d.Key==ViewBag.Connid?"selected=selected":"") >@d.Value.name</option>
                            }
                        </select>
                        <input type="submit" class="btn1" value="搜索" accesskey="S" />
                    </li>
                </ul>
            </div>
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

Monitor.Web/Areas/TimeWatchCustomer/Views/SqlHashContrastUrl/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Monitor.Domain.TimeWatch.Model.tb_sqlhash_url_contrast_model>
@using BSF.Extensions;
<style>
    tr b {
        color: black;
    }

    tr .order {
        color: red;
    }
</style>
<table class="mytable">
    <tr>
        
        <th style="width:100px;">URL</th>
        <th style="width:80px;">SQLHASH</th>
        <th style="">SQL</th>
        <th style="width:80px;">最新日期</th>
        <th style="width:100px;">时间(s)</th>
        <th style="width:90px;">操作</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
           
            
            <td><b @Html.Raw((ViewBag.orderby).ToLower() == "" ? "class='order'" : "")>@item.url</b></td>
            <td><a href="@Url.Action("Chart", "TimeWatchLog", new { Area = "TimeWatchCustomer", logtag = item.sqlhash, type = (int)BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd, connid = ViewBag.Connid, date = item.date.ToString("yyyy-MM-dd"), datatype = "avg" })" title="点击查看性能图" target="_blank">@item.sqlhash</a></td>
            <td title="@item.sql">@item.sql.SubString3(100)@Html.Raw(string.IsNullOrWhiteSpace(item.sql.SubString3(100)) ? string.Format("<a href='/TimeWatchCustomer/TimeWatchLog?timebegin={0}&timeend={1}&logtag={2}&connid={3}&logtype={4}' target='_blank'>找不到sql?</a>"
            , item.date.ToString("yyyy-MM-dd HH:mm:ss"), item.date.ToString("yyyy-MM-dd") + " 23:59:59", item.sqlhash, ViewBag.Connid, (int)BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd) : "")</td>
             <td>@item.date.ToString("yyyy-MM-dd")</td>
            <td style="text-align:left"><b @Html.Raw((ViewBag.orderby).ToLower() == "avgtime" ? "class='order'" : "")>平均:@item.avgtime.ToString("f3")</b>(s)<br/>
            <b @Html.Raw((ViewBag.orderby).ToLower() == "maxtime" ? "class='order'" : "")>最大:@item.maxtime.ToString("f3")</b>(s)<br/>
            <b @Html.Raw((ViewBag.orderby).ToLower() == "mintime" ? "class='order'" : "")>最小:@item.mintime.ToString("f3")</b>(s)<br/>
            <b @Html.Raw((ViewBag.orderby).ToLower() == "count" ? "class='order'" : "")>调用:@item.count</b>(次)</td>
            <td class="caozuo">
                <a href="@Url.Action("Index", "SqlHashContrastUrl", new { Area = "TimeWatchCustomer", url = item.url, connid = ViewBag.Connid })" target="_blank">api相关sql</a><br/>
                <a href="@Url.Action("Chart", "TimeWatchLog", new { Area="TimeWatchCustomer",logtag=item.url,type=(int)BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.ApiUrl,connid=ViewBag.Connid,date=item.date.ToString("yyyy-MM-dd"),datatype="avg" })" target="_blank">api性能图</a><br/>
                <a href="@Url.Action("Chart", "TimeWatchLog", new { Area="TimeWatchCustomer",logtag=item.sqlhash,type=(int)BSF.BaseService.Monitor.SystemRuntime.EnumTimeWatchLogType.SqlCmd,connid=ViewBag.Connid,date=item.date.ToString("yyyy-MM-dd"),datatype="avg" })" target="_blank">sql性能图</a><br/>
                <a href="@Url.Action("Index", "TimeWatchLogSqlDayReport", new { Area="TimeWatchCustomer",sqlhash=item.sqlhash,connid=ViewBag.Connid,datatype="avg",timebegin=DateTime.Now.ToString("yyyy-MM-01"),timeend=DateTime.Now.ToString("yyyy-MM-dd") })"  target="_blank">当月耗时</a>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>